---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/
- test/
