sudo: required
language: node_js

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x

node_js:
  - '4'

cache:
  directories:
  - node_modules

services:
  - docker

before_script:
  - docker-compose start neo4j
  - docker-compose start store

after_script:
  - docker-compose stop