store:
 build: .
 links:
  - neo4j
 volumes:
  - $PWD:/home/redjam/src
 user: redjam
 command: bash -c "cd /home/redjam/src && whoami && ls -la && npm install && npm test"

neo4j:
 image: neo4j:2.3.2
 ports: 
  - "7474:7474"
  - "7473:7473"
 environment:
  - NEO4J_AUTH=neo4j/seneca_test