server:
 build: .
 links:
  - neo4j
 volumes:
  - $PWD:/home/redjam/src
 command: bash -c "cd /home/redjam/src && npm install && npm test && npm run coverage"

neo4j:
 image: neo4j:2.3.2
 ports: 
  - "7474:7474"
  - "7473:7473"
