store:
 build: .
 dockerfile: dev-Dockerfile
 volumes:
  - $PWD:/home/dogfish/src
 links:
  - neo4j
 command: ash -c "cd /home/dogfish/src && npm install && npm install --only=dev && npm install seneca${SENECA_VER} && nodemon -L --ignore '*.test.js' ./neo4j-store.js"

test:
 build: .
 links:
  - neo4j
 user: dogfish
 command: ash -c "cd /home/dogfish/src && npm install && npm install --only=dev && npm install seneca${SENECA_VER} && npm test && npm run coverage"

coverage:
 build: .
 volumes:
  - $PWD/coverage:/home/dogfish/src/coverage
 links:
  - neo4j
 user: dogfish
 command: ash -c "cd /home/dogfish/src && npm install && npm install --only=dev && npm install seneca${SENECA_VER} && npm run coverage"

neo4j:
 image: neo4j:2.3.2
 ports: 
  - "7474:7474"
  - "7473:7473"
 environment:
  - NEO4J_AUTH=neo4j/seneca_test